### ISSUE TITLE
Can't Build the project on Android Studio

### ISSUE THREAD

**Issue by burnerlee** [Techno-Disaster/Invoice#1]
It gives me a build error, nor i could debug on my phone.
```Error:Internal error: (java.lang.ClassNotFoundException) com.google.wireless.android.sdk.stats.IntellijIndexingStats$Index
java.lang.ClassNotFoundException: com.google.wireless.android.sdk.stats.IntellijIndexingStats$Index
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:419)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:352)
	at com.intellij.util.indexing.counters.IndexCounters.<clinit>(IndexCounters.java:34)
	at com.intellij.util.indexing.impl.MapReduceIndex.<init>(MapReduceIndex.java:92)
	at com.intellij.util.indexing.impl.MapReduceIndex.<init>(MapReduceIndex.java:108)
	at org.jetbrains.jps.backwardRefs.index.CompilerReferenceIndex$CompilerMapReduceIndex.<init>(CompilerReferenceIndex.java:274)
	at org.jetbrains.jps.backwardRefs.index.CompilerReferenceIndex.<init>(CompilerReferenceIndex.java:110)
	at org.jetbrains.jps.backwardRefs.JavaCompilerBackwardReferenceIndex.<init>(JavaCompilerBackwardReferenceIndex.java:13)
	at org.jetbrains.jps.backwardRefs.JavaBackwardReferenceIndexWriter.initialize(JavaBackwardReferenceIndexWriter.java:80)
	at org.jetbrains.jps.incremental.java.JavaBuilder.buildStarted(JavaBuilder.java:152)
	at org.jetbrains.jps.incremental.IncProjectBuilder.runBuild(IncProjectBuilder.java:361)
	at org.jetbrains.jps.incremental.IncProjectBuilder.build(IncProjectBuilder.java:178)
	at org.jetbrains.jps.cmdline.BuildRunner.runBuild(BuildRunner.java:140)
	at org.jetbrains.jps.cmdline.BuildSession.runBuild(BuildSession.java:297)
	at org.jetbrains.jps.cmdline.BuildSession.run(BuildSession.java:130)
	at org.jetbrains.jps.cmdline.BuildMain$MyMessageHandler.lambda$channelRead0$0(BuildMain.java:232)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)```

**Comment by techno-disaster** [comment]
Hey @burnerlee this is a flutter app. I guess you are trying to build it using Java/Kotlin?

**Comment by burnerlee** [comment]
umm. not exactly i am new to android and i am using android studio api 30 i guess... can you help me in setting it up?

**Comment by burnerlee** [comment]
thank you for the prompt reply btw :smile:

**Comment by techno-disaster** [comment]
> umm. not exactly i am new to android and i am using android studio api 30 i guess... can you help me in setting it up?

I would suggest you install the Flutter sdk from flutter.dev first

**Comment by burnerlee** [comment]
@Techno-Disaster, i have installed flutter, but when i try to run your app, it gives errors regarding the Page component.

**Comment by burnerlee** [comment]
```The name 'Page' is defined in the libraries 'package:flutter/src/widgets/navigator.dart' and 'package:scanbot_sdk/common_data.dart'.```

**Comment by burnerlee** [comment]
![Screenshot from 2020-08-04 23-19-18](https://user-images.githubusercontent.com/55936223/89327158-12b6ac00-d6a9-11ea-951a-3118b828cc86.png)
Getting these warnings on running this app.
Also stuck forever on...
```Launching lib/main.dart on HD1901 in debug mode...
Running Gradle task 'assembleDebug'...```
Please help @Techno-Disaster

**Comment by burnerlee** [comment]
Can you please provide with the APK of this project?

**Comment by burnerlee** [comment]
Cool, your project yours after a few changes.... but the license key is expired... i got a new key from scanbot site..... and changed it with the existing license key..... but there is an error of initialising the License Key.

**Comment by burnerlee** [comment]
@Techno-Disaster

**Comment by techno-disaster** [comment]
what error? logs please

**Comment by burnerlee** [comment]
Okay i worked them on a bit(had to call initConfigs at a place).... but can you get me a license key or renew in your repo... whenever it try to get new keys from scanbot sdk (for pkg name:`com.example.invoicescan`).... it gives me an error:
```
[        ] E/SDK     (23929): java.lang.RuntimeException: ScanbotSDK: ERROR - ScanbotSDK license doesn't match to the application bundle ID/package name.
[        ] I/flutter (23929): PlatformException(RuntimeException, ScanbotSDK: ERROR - ScanbotSDK license doesn't match to the application bundle ID/package name., null)
[        ] I/flutter (23929): PlatformException(RuntimeException, ScanbotSDK: ERROR - ScanbotSDK license doesn't match to the application bundle ID/package name., null)
```

**Comment by burnerlee** [comment]
i have also tried using pkg names as: `com.example.InvoiceScan` and `com.example.scanbot_sdk_example_flutter` but the same error. @Techno-Disaster

**Comment by techno-disaster** [comment]
@burnerlee use will be able to find this id in android>app>src>main>Android Manifest

**Comment by burnerlee** [comment]
Are you talking about `com.example.scanbot_sdk_example_flutter`? Please mention the id of project here in the comments. I have tried with everything i found.. or please provide with a new license key.... I really spent a lot of hours trying to fix this. @Techno-Disaster

**Comment by techno-disaster** [comment]
yep, that the id, feel free to ping me if you are still stuck

**Comment by burnerlee** [comment]
Yes @Techno-Disaster this doesn't work gives me the same error that package name doesn't match with the license key

**Comment by burnerlee** [comment]
Can you please generate a license key for the same?

**Comment by techno-disaster** [comment]
Ok will do soon. Occupied atm

**Comment by burnerlee** [comment]
@Techno-Disaster please update the license keys.. I need to refer to your project for some project I am building and I need to submit it shortly
